os: linux
dist: focal
language: generic

script: true

notifications:
  irc: 
    channels: 
      - "chat.freenode.net#qasim-travis-test"
    use_notice: true
    on_success: always
    on_failure: always